// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymkkhjhunndtxcfmlhjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlta2toamh1bm5kdHhjZm1saGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTY5NTcsImV4cCI6MjA2NDY3Mjk1N30.kHCRBYsLs835FJdfabzPXY4mpZkwh__kjWUFJjqTcrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);